name: Continuous OCI Python SDK Provisioner Loop
on:
  schedule:
    - cron: '0 * * * *'  # හැම පැයකට වරක් පමණක් ක්‍රියාත්මක වේ
  workflow_dispatch:

# මෙය එකතු කිරීමෙන් එකවර කීපයක් run වීම නැවතී GitHub account එක ban වීම වැලැක්වේ
concurrency:
  group: oci-provisioner
  cancel-in-progress: true 

jobs:
  attempt-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install SDK Requirements
        run: pip install -r requirements.txt

      - name: Execute Python Provisioning Engine
        env:
          PYTHONUNBUFFERED: "1"
          OCI_USER_ID: ${{ secrets.OCI_USER_ID }}
          OCI_PRIVATE_KEY: ${{ secrets.OCI_PRIVATE_KEY }}
          OCI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
          OCI_TENANCY_ID: ${{ secrets.OCI_TENANCY_ID }}
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_SUBNET_ID: ${{ secrets.OCI_SUBNET_ID }}
          OCI_IMAGE_ID: ${{ secrets.OCI_IMAGE_ID }}
          OCI_PUBLIC_SSH_KEY: ${{ secrets.OCI_PUBLIC_SSH_KEY }} 
        run: python "bot.py"
